spring.application.name=UserService
spring.datasource.url=jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5432}/postgres?currentSchema=user_db
spring.datasource.username=${POSTGRES_DB_USERNAME:admin}
spring.datasource.password=${POSTGRES_DB_PASSWORD:sql}
spring.jpa.hibernate.ddl-auto=update
server.port=8081
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:${KEYCLOAK_BASE_URL:http://localhost:9090}/realms/${KEYCLOAK_REALM:starter-dev}}

keycloak.server-url=${KEYCLOAK_BASE_URL:http://localhost:9090}
keycloak.realm=${KEYCLOAK_REALM:starter-dev}
keycloak.client-id=backend-client
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:example-secrer}
